owner    = "kowainik"
fullName = "Kowainik"
email    = "xrom.xkov@gmail.com"
license  = "MPL-2.0"
ghcVers  = ["8.0.2"]
bscript  = false
lib      = true
test     = true
github   = true
travis   = true
